"""alter table category

Revision ID: 1b47d39b468a
Revises: e8e37b21ceab
Create Date: 2023-12-20 13:25:14.059709

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1b47d39b468a'
down_revision = 'e8e37b21ceab'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Categories', schema=None) as batch_op:
        batch_op.add_column(sa.Column('category_name', sa.String(length=50), nullable=False))
        batch_op.drop_column('currency_name')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Categories', schema=None) as batch_op:
        batch_op.add_column(sa.Column('currency_name', sa.VARCHAR(length=50), autoincrement=False, nullable=False))
        batch_op.drop_column('category_name')

    # ### end Alembic commands ###
