"""update tables

Revision ID: 39b2deae7cac
Revises: f6c6769b5680
Create Date: 2023-12-13 21:44:22.135134

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '39b2deae7cac'
down_revision = 'f6c6769b5680'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Departments', schema=None) as batch_op:
        batch_op.alter_column('department_address',
               existing_type=sa.VARCHAR(length=200),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Departments', schema=None) as batch_op:
        batch_op.alter_column('department_address',
               existing_type=sa.VARCHAR(length=200),
               nullable=False)

    # ### end Alembic commands ###
