"""update table rates

Revision ID: 3a538d31658d
Revises: d8c746c0f0d0
Create Date: 2023-12-23 02:38:23.460607

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3a538d31658d'
down_revision = 'd8c746c0f0d0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('ratetypes')
    with op.batch_alter_table('CurrencyRates', schema=None) as batch_op:
        batch_op.add_column(sa.Column('rate_type', sa.Integer(), nullable=False))
        batch_op.create_foreign_key(None, 'RateTypes', ['rate_type'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('CurrencyRates', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('rate_type')

    op.create_table('ratetypes',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.PrimaryKeyConstraint('id', name='ratetypes_pkey')
    )
    # ### end Alembic commands ###
