"""update deposits

Revision ID: 3be5cf294a6e
Revises: ae8b55ae7cf5
Create Date: 2023-12-24 18:02:00.712911

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3be5cf294a6e'
down_revision = 'ae8b55ae7cf5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Deposits', schema=None) as batch_op:
        batch_op.drop_column('deposit_amount')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Deposits', schema=None) as batch_op:
        batch_op.add_column(sa.Column('deposit_amount', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))

    # ### end Alembic commands ###
