"""update deposits

Revision ID: 3d1ecaae744c
Revises: 3be5cf294a6e
Create Date: 2023-12-24 18:03:13.563442

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3d1ecaae744c'
down_revision = '3be5cf294a6e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Deposits', schema=None) as batch_op:
        batch_op.drop_column('interest_rate')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Deposits', schema=None) as batch_op:
        batch_op.add_column(sa.Column('interest_rate', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))

    # ### end Alembic commands ###
