"""update credits

Revision ID: 4001d3ae4949
Revises: 92e4ddb29707
Create Date: 2023-12-24 22:17:33.796811

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4001d3ae4949'
down_revision = '92e4ddb29707'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Credits', schema=None) as batch_op:
        batch_op.alter_column('request_id',
               existing_type=sa.INTEGER(),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Credits', schema=None) as batch_op:
        batch_op.alter_column('request_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###
