"""update Users

Revision ID: 71e7efbe92e3
Revises: 577c1b884325
Create Date: 2023-12-13 05:19:19.297568

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '71e7efbe92e3'
down_revision = '577c1b884325'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Clients', schema=None) as batch_op:
        batch_op.alter_column('pref_currency_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Clients', schema=None) as batch_op:
        batch_op.alter_column('pref_currency_id',
               existing_type=sa.INTEGER(),
               nullable=False)

    # ### end Alembic commands ###
