"""update transfer

Revision ID: 81774b53abf0
Revises: a6aa32fadfd3
Create Date: 2023-12-25 21:36:59.708988

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '81774b53abf0'
down_revision = 'a6aa32fadfd3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('TransferRequests', schema=None) as batch_op:
        batch_op.add_column(sa.Column('transaction_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('status', sa.Boolean(), nullable=True))
        batch_op.create_foreign_key(None, 'Transactions', ['transaction_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('TransferRequests', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('status')
        batch_op.drop_column('transaction_id')

    # ### end Alembic commands ###
