"""update table rates

Revision ID: 8298ae6dc7b2
Revises: 3a538d31658d
Create Date: 2023-12-23 02:39:08.564775

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8298ae6dc7b2'
down_revision = '3a538d31658d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('RateTypes')
    with op.batch_alter_table('CurrencyRates', schema=None) as batch_op:
        batch_op.add_column(sa.Column('scale', sa.Integer(), nullable=True))
        batch_op.drop_constraint('CurrencyRates_rate_type_fkey', type_='foreignkey')
        batch_op.drop_column('rate_type')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('CurrencyRates', schema=None) as batch_op:
        batch_op.add_column(sa.Column('rate_type', sa.INTEGER(), autoincrement=False, nullable=False))
        batch_op.create_foreign_key('CurrencyRates_rate_type_fkey', 'RateTypes', ['rate_type'], ['id'])
        batch_op.drop_column('scale')

    op.create_table('RateTypes',
    sa.Column('id', sa.INTEGER(), server_default=sa.text('nextval(\'"RateTypes_id_seq"\'::regclass)'), autoincrement=True, nullable=False),
    sa.Column('type_name', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='RateTypes_pkey')
    )
    # ### end Alembic commands ###
