"""update credits

Revision ID: a5bd80883d16
Revises: 94d4b4d5d0b4
Create Date: 2023-12-24 22:05:42.639356

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a5bd80883d16'
down_revision = '94d4b4d5d0b4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Credits', schema=None) as batch_op:
        batch_op.add_column(sa.Column('request_id', sa.Integer(), nullable=False))
        batch_op.create_foreign_key(None, 'CreditsRequests', ['request_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Credits', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('request_id')

    # ### end Alembic commands ###
