"""update transfer

Revision ID: a6aa32fadfd3
Revises: 16f9346ed20d
Create Date: 2023-12-25 21:04:32.547634

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a6aa32fadfd3'
down_revision = '16f9346ed20d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('TransferRequests', schema=None) as batch_op:
        batch_op.add_column(sa.Column('to_user', sa.String(length=50), nullable=False))
        batch_op.drop_column('from_user')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('TransferRequests', schema=None) as batch_op:
        batch_op.add_column(sa.Column('from_user', sa.VARCHAR(length=50), autoincrement=False, nullable=False))
        batch_op.drop_column('to_user')

    # ### end Alembic commands ###
