"""update deposits

Revision ID: ae8b55ae7cf5
Revises: 81df1aec1262
Create Date: 2023-12-24 17:11:02.120442

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ae8b55ae7cf5'
down_revision = '81df1aec1262'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('DepositTypes', schema=None) as batch_op:
        batch_op.drop_column('max_amount')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('DepositTypes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('max_amount', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))

    # ### end Alembic commands ###
