"""update credit requests

Revision ID: c5c2c80f255f
Revises: 
Create Date: 2023-12-20 08:48:53.565891

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c5c2c80f255f'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('CreditsRequests', schema=None) as batch_op:
        batch_op.add_column(sa.Column('amount', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('interest_rate', sa.Float(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('CreditsRequests', schema=None) as batch_op:
        batch_op.drop_column('interest_rate')
        batch_op.drop_column('amount')

    # ### end Alembic commands ###
