"""update currency

Revision ID: cfcd86c5b498
Revises: 4001d3ae4949
Create Date: 2023-12-25 01:49:28.143552

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cfcd86c5b498'
down_revision = '4001d3ae4949'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('CurrencyRates', schema=None) as batch_op:
        batch_op.drop_column('scale')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('CurrencyRates', schema=None) as batch_op:
        batch_op.add_column(sa.Column('scale', sa.INTEGER(), autoincrement=False, nullable=True))

    # ### end Alembic commands ###
