"""update credic schema

Revision ID: d8c746c0f0d0
Revises: 1b47d39b468a
Create Date: 2023-12-23 00:09:22.477010

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd8c746c0f0d0'
down_revision = '1b47d39b468a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('CreditsRequests', schema=None) as batch_op:
        batch_op.add_column(sa.Column('type_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'CreditTypes', ['type_id'], ['id'])
        batch_op.drop_column('interest_rate')
        batch_op.drop_column('date_term')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('CreditsRequests', schema=None) as batch_op:
        batch_op.add_column(sa.Column('date_term', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('interest_rate', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('type_id')

    # ### end Alembic commands ###
