"""update credit requests

Revision ID: e8e37b21ceab
Revises: c5c2c80f255f
Create Date: 2023-12-20 08:59:04.076831

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e8e37b21ceab'
down_revision = 'c5c2c80f255f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('CreditsRequests', schema=None) as batch_op:
        batch_op.add_column(sa.Column('date_term', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('CreditsRequests', schema=None) as batch_op:
        batch_op.drop_column('date_term')

    # ### end Alembic commands ###
