"""update Client

Revision ID: f6c6769b5680
Revises: 8bbf076683e9
Create Date: 2023-12-13 16:05:34.872338

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f6c6769b5680'
down_revision = '8bbf076683e9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Clients', schema=None) as batch_op:
        batch_op.drop_constraint('Clients_pref_currency_id_fkey', type_='foreignkey')
        batch_op.drop_column('pref_currency_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Clients', schema=None) as batch_op:
        batch_op.add_column(sa.Column('pref_currency_id', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.create_foreign_key('Clients_pref_currency_id_fkey', 'Currencies', ['pref_currency_id'], ['id'])

    # ### end Alembic commands ###
